// GENERATED by scripts/sync-mudlet-games.mjs — do not edit by hand.
//
// The games Mudlet ships with, vendored from its src/TGameDetails.h. mudix needs
// the same catalogue for two reasons: the connection dialog offers the same
// games, and Mudlet's profile-description API answers for a bundled game's name
// whether or not a profile of that name exists — a script asking about "Achaea"
// gets the blurb, not nil.
//
// Regenerate with: node scripts/sync-mudlet-games.mjs [path/to/TGameDetails.h]

/** One entry of Mudlet's bundled-game catalogue (its C++ `GameDetail`). */
export interface BundledGame {
    name: string;
    hostUrl: string;
    port: number;
    tlsEnabled: boolean;
    /** Small HTML fragment of website/forum/Discord links. */
    websiteInfo: string;
    /** Qt resource path of the game's icon, kept as the upstream identifier. */
    icon: string;
    /** Filename of the copy vendored in ./icons/, when one was available.
     *  Resolve it with `gameIconUrl()` rather than building a path by hand —
     *  the bundler only emits assets it can see referenced. */
    iconFile?: string;
    description: string;
    /** The game's own loader installs its full interface, so the generic
     *  starter UI is not preinstalled for it. */
    providesOwnUi?: boolean;
    /** Other hostnames the game answers on. */
    alternateHostUrls?: string[];
}

export const BUNDLED_GAMES: readonly BundledGame[] = [
    {
        "name": "Mudlet Tutorial",
        "hostUrl": "localhost",
        "port": 0,
        "tlsEnabled": false,
        "websiteInfo": "<a href='https://mudlet.org'>Website</a><br><a href='https://wiki.mudlet.org'>Wiki</a>",
        "icon": ":/icons/mudlet-tutorial.png",
        "description": "Mudlet provides a simple tutorial to help you get familiar with playing MUDs using Mudlet.\n\nYou play a young adventurer who has recently graduated from the adventuring school.  You must aid the Sheriff in a series of tasks for the townfolk and become a local hero.",
        "iconFile": "mudlet-tutorial.png"
    },
    {
        "name": "Abandoned Realms",
        "hostUrl": "abandonedrealms.com",
        "port": 9000,
        "tlsEnabled": false,
        "websiteInfo": "<a href='https://abandonedrealms.com'>Website</a><br><a href='https://abandonedrealms.com/forum'>Forum</a>",
        "icon": ":/icons/abandonedrealms_icon.jpg",
        "description": "The Abandoned Realms is a completely free RP-enforced, PK-encouraged, MUD in a fantasy setting (swords/magic/lore/intrigue) that has been up and running constantly since 1997.\n\nWith 20 races and 16 classes, there are vast possibilities for players to explore and enjoy. The Abandoned Realms has a dedicated staff of highly skilled immortals/coders/builders, and a diverse base players online at any given time. There are extensive opportunities for role-play, including writing character background entries, building your own house (including decor), contributing to the in-game newspaper, engaging in political intrigue, choosing a deity to worship (and opening exceptional Immortal RP opportunities), and more.\n\nIt is a dangerous realm, filled with exceptional killers but new players are not hunted – they are welcomed and supported. Perma-death exists, but it is common for characters to live for hundreds of  hours, or as long as the player desires. Information and advice are shared freely – see The Codex for item identifications/locations, the logboard for battles, and the forum and discord for gameplay discussion and advice.\n\nIf you are interested in a completely free, immersive RP/PK experience, in a vibrant land filled with lore/intrigue, where you can forge long-lasting friendships and bitter rivalries, and have an opportunity to leave your lasting mark and be remembered forever, then welcome ye to the Abandoned Realms.",
        "iconFile": "abandonedrealms_icon.jpg"
    },
    {
        "name": "Avalon.de",
        "hostUrl": "avalon.mud.de",
        "port": 23,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://avalon.mud.de'>http://avalon.mud.de</a>",
        "icon": ":/icons/avalon.png",
        "description": "",
        "iconFile": "avalon.png"
    },
    {
        "name": "Achaea",
        "hostUrl": "achaea.com",
        "port": 23,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://www.achaea.com/'>Website</a><br><a href='https://discord.gg/2v2upFTj8G'>Discord</a>",
        "icon": ":/icons/achaea.png",
        "description": "In Achaea, your name carries weight.\n\nSome worlds are easy to leave behind. Achaea is not one of them. The cities, the Houses, the rivalries, the faith, the politics all create the social gravity veterans remember.\n\nReputation matters here. History lingers. What you do shapes how people know you.\n\nCome back to a world where identity means more than a build.",
        "iconFile": "achaea.png"
    },
    {
        "name": "3Kingdoms",
        "hostUrl": "3k.org",
        "port": 3000,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://www.3k.org/'>http://www.3k.org</a>",
        "icon": ":/icons/3Kingdoms.png",
        "description": "Simple enough to learn, yet complex enough to challenge you for years, 3Kingdoms is a colossal adventure through which many years of active and continued development by its dedicated coding staff.  Based around the mighty town of Pinnacle, three main realms beckon the player to explore. These kingdoms are known as: Fantasy, a vast medieval realm full of orcs, elves, dragons, and a myriad of other creatures; Science, a post-apocalyptic, war-torn world set in the not-so-distant future; and Chaos, a transient realm where the enormous realities of Fantasy and Science collide to produce creatures so bizarre that they have yet to be categorized.  During their exploration of the realms, players have the opportunity to join any of well over a dozen different guilds, which grant special, unique powers to the player, furthering their abilities as they explore the vast expanses of each realm. Add in the comprehensive skill system that 3K offers and you are able to extensively customize your characters.",
        "iconFile": "3Kingdoms.png"
    },
    {
        "name": "3Scapes",
        "hostUrl": "3k.org",
        "port": 3200,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://www.3scapes.org/'>http://www.3scapes.org</a>",
        "icon": ":/icons/3Scapes.png",
        "description": "3Scapes is an alternative dimension to 3Kingdoms, similar in many respects, but unique and twisted in so many ways.  3Scapes offers a faster pace of play, along with an assortment of new guilds, features, and areas.",
        "iconFile": "3Scapes.png"
    },
    {
        "name": "Lusternia",
        "hostUrl": "lusternia.com",
        "port": 5000,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://www.lusternia.com/'>Website</a><br><a href='https://discord.gg/d8PECxD739'>Discord</a>",
        "icon": ":/icons/lusternia.png",
        "description": "Lusternia feels like nowhere else.\n\nNot because it tries to be strange for its own sake, but because it never settled for ordinary. The planes are stranger. The lore runs deeper. The factions feel less familiar, and the world keeps opening up long after the first impression.\n\nVeterans do not come back to Lusternia for comfort. They come back for discovery.\n\nEnter a world that keeps revealing more of itself.",
        "iconFile": "lusternia.png"
    },
    {
        "name": "BatMUD",
        "hostUrl": "batmud.bat.org",
        "port": 23,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://www.bat.org'>http://www.bat.org</a>",
        "icon": ":/icons/batmud_mud.png",
        "description": "",
        "iconFile": "batmud_mud.png"
    },
    {
        "name": "DarkMists",
        "hostUrl": "darkmists.org",
        "port": 2222,
        "tlsEnabled": false,
        "websiteInfo": "<a href='https://darkmists.org'>https://darkmists.org</a>",
        "icon": ":/icons/banner_darkmists.png",
        "description": "Dark Mists is a persistent online fantasy world featuring 24 races and 11 classes, 9 of which branch into distinct subclasses, with dozens of quests and hundreds of skills and spells tied to class, subclass, or race. The world is shaped by the players through active clans and a worship system with direct interaction with the Gods of Dark Mists. The Immortals are present in-game and continue developing new content for the world. The community is welcoming and helpful to newcomers while encouraging competition and growth. Houses remain active and provide guidance and support for new and returning players. Roleplay is required and playerkilling is an integral part of character growth, rewarding wit, courage, and ambition. The world continues to evolve with new discoveries and challenges. Come carve out your legacy in Dark Mists.",
        "iconFile": "banner_darkmists.png"
    },
    {
        "name": "God Wars II",
        "hostUrl": "godwars2.org",
        "port": 3000,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://www.godwars2.org'>http://www.godwars2.org</a>",
        "icon": ":/icons/gw2.png",
        "description": "God Wars II is a fast and furious combat mud, designed to test player skill in terms of pre-battle preparation and on-the-spot reflexes, as well as the ability to adapt quickly to new situations. Take on the role of a godlike supernatural being in a fight for supremacy.\n\nRoomless world. Manual combat. Endless possibilities.",
        "iconFile": "gw2.png"
    },
    {
        "name": "Slothmud",
        "hostUrl": "slothmud.org",
        "port": 6101,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://www.slothmud.org/'>http://www.slothmud.org/</a>",
        "icon": ":/icons/Slothmud.png",
        "description": "SlothMUD... the ultimate in DIKUMUD! The most active, intricate, exciting FREE MUD of its kind. This text based multiplayer free online rpg game and is enjoyed continuously by players worldwide. With over 27,500 uniquely described rooms, 9,300 distinct creatures, 14,200 characters, and 87,100 pieces of equipment, charms, trinkets and other items, our online rpg world is absolutely enormous and ready to explore.",
        "iconFile": "Slothmud.png"
    },
    {
        "name": "Aardwolf",
        "hostUrl": "aardmud.org",
        "port": 4000,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://www.aardwolf.com/'>http://www.aardwolf.com</a>",
        "icon": ":/icons/aardwolf_mud.png",
        "description": "",
        "iconFile": "aardwolf_mud.png"
    },
    {
        "name": "Materia Magica",
        "hostUrl": "materiamagica.com",
        "port": 23,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://www.materiamagica.com'>http://www.materiamagica.com</a>",
        "icon": ":/materiaMagicaIcon",
        "description": "",
        "iconFile": "logo_mm-120x30px-verticalBlackBgd.png"
    },
    {
        "name": "Mudren",
        "hostUrl": "mud.ren",
        "port": 6666,
        "tlsEnabled": false,
        "websiteInfo": "<a href='https://mud.ren/'>https://mud.ren/</a>",
        "icon": ":/icons/mudren.png",
        "description": "天下风云出我辈，一入江湖岁月催。\n皇图霸业谈笑中，不胜人生一场醉。\n提剑跨骑挥鬼雨，白骨如山鸟惊飞。\n尘事如潮人如水，只叹江湖几人回。\n\n中文开源武侠MUD炎黄群侠传，游戏包括25大门派和5大世家，正邪只在一念间；近千门武学等你学习，上百种任务随你体验；让自己成为一代宗师，江湖笑，恩怨了。",
        "iconFile": "mudren.png"
    },
    {
        "name": "Petria",
        "hostUrl": "game.petriamud.com",
        "port": 6600,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://www.petriamud.com'>www.petriamud.com</a><br><a href='https://www.youtube.com/channel/UCqXqG9qG6L1q3Q3F4F6Q6Nw'>Petria - YouTube</a>",
        "icon": ":/icons/banner_petria.jpg",
        "description": "Petria MUD Activo desde 1996, es uno de los juegos en Español más longevos y con comunidad activa hasta hoy. Un mundo de fantasía gratuito donde podrás jugar distintas razas y clases, unirte a clanes, explorar, participar en torneos y vivir aventuras épicas.\n\n• Gratis y en Español.\n• Eventos dinámicos: Torneos, Asaltos de Clanes, BattleGrounds (War of Flags), Quests, entre otros.\n• Más de dos décadas de historia, con constantes mejoras y nuevos contenidos.\n\nEn Petria podrás forjar tu camino, defender a tu clan y escribir tu propia leyenda.",
        "iconFile": "banner_petria.jpg"
    },
    {
        "name": "Realms of Despair",
        "hostUrl": "realmsofdespair.com",
        "port": 4000,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://www.realmsofdespair.com/'>http://www.realmsofdespair.com</a>",
        "icon": ":/icons/120x30RoDLogo.png",
        "description": "The Realms of Despair is the original SMAUG MUD and is FREE to play. We have an active Roleplaying community, an active player-killing (deadly) community, and a very active peaceful community. Players can choose from 13 classes (including a deadly-only class) and 13 races. Character appearances are customizable on creation and we have a vast collection of equipment that is level, gender, class, race and alignment specific. We boast well over 150 original, exclusive areas, with a total of over 20,000 rooms. Mob killing, or 'running' is one of our most popular activities, with monster difficulties varying from easy one-player kills to difficult group kills. We have four deadly-only Clans, twelve peaceful-only Guilds, eight Orders, and fourteen Role-playing Nations that players can join to interact more closely with other players. We have two mortal councils that actively work toward helping players: The Symposium hears ideas for changes, and the Newbie Council assists new players. Our team of Immortals are always willing to answer questions and to help out however necessary. Best of all, playing the Realms of Despair is totally FREE!",
        "iconFile": "120x30RoDLogo.png"
    },
    {
        "name": "Rites of Passage MUD",
        "hostUrl": "play.ropmud.com",
        "port": 4443,
        "tlsEnabled": false,
        "websiteInfo": "<a href='https://ropmud.com/index.html'>Website</a><br><a href='https://discord.gg/CkYm9WRnyw'>Discord</a>",
        "icon": ":/icons/banner_ropmud.png",
        "description": "Rites of Passage is a PVPVE (Player vs Player vs Environment) MUD where Good and Evil are locked in eternal war. Hunt powerful monsters for legendary loot, then defend it from enemy players hunting you. Every expedition into dangerous territory carries the thrill of both PvE challenge and PvP risk.\n\nThe environment is deadly - 80+ areas filled with creatures guarding valuable equipment, quests that reward the bold, and a remort system that lets you grow stronger with each life. But the real tension comes from other players. That raid boss you're fighting? The enemy faction might be watching, waiting for you to weaken before they strike. That rare gem you just looted? You'll need to make it home alive.\n\nThis is a PK MUD. Combat between Good and Evil players isn't just allowed - it's encouraged. Killing enemies earns warpoints, experience, and their gear. Climb the ranks. Make the topten list. Build your reputation through conquest. If you want the risk of PvP combined with challenging environment combat, you've found your home.",
        "iconFile": "banner_ropmud.png"
    },
    {
        "name": "ZombieMUD",
        "hostUrl": "zombiemud.org",
        "port": 3000,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://www.zombiemud.org/'>http://www.zombiemud.org</a>",
        "icon": ":/icons/zombiemud.png",
        "description": "Since 1994, ZombieMUD has been on-line and bringing orc-butchering fun to the masses from our home base in Oulu, Finland. We're a pretty friendly bunch, with players logging in from all over the globe to test their skill in our medieval role-playing environment. With 15 separate guilds and 41 races to choose from, as a player the only limitation to your achievements on the game is your own imagination and will to succeed.",
        "iconFile": "zombiemud.png"
    },
    {
        "name": "Aetolia",
        "hostUrl": "aetolia.com",
        "port": 23,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://www.aetolia.com/'>Website</a><br><a href='https://discord.gg/x2s7fY6'>Discord</a>",
        "icon": ":/icons/aetolia.png",
        "description": "Aetolia does not do safe fantasy.\n\nIt never did.\n\nThis is a world of darkness, pressure, factional loyalty, and choices that leave scars. Allegiance matters. Hostility kills. The atmosphere is not decoration. It is part of the threat.\n\nStep back into a world that does not let you stay comfortable.",
        "iconFile": "aetolia.png"
    },
    {
        "name": "Astaria",
        "hostUrl": "astaria.net",
        "port": 5000,
        "tlsEnabled": false,
        "websiteInfo": "<a href='https://astariamud.com'>astariamud.com</a>",
        "icon": ":/icons/banner_astaria.png",
        "description": "Once more unto the breach, dear friends...\n\nWelcome Traveller, your sojourn awaits. Only one step remains between you and a realm where your mind can soar, unbound from the fetters of the mundane world.\n\nLet your spirit take shape in one of fifteen races, cast your will into one of nine guilds and begin your journey towards destiny. Forge friendships. Gain power. Vanquish enemies. Work with your allies toward goals greater than yourself. Become part of the rich history of adventurers who have made their home in a world that is immediately fun and will continue to challenge and stimulate for years to come. Step through the portal, and immerse yourself in the mythical world, Astaria.\n\nAstaria is a free-to-play MUD with an RP-optional atmosphere, set in a medieval fantasy world with a touch of cosmic horror. Active since 1994, it's a realm where dragons still roam, adventures await around every corner, and new heroes are always welcome.",
        "iconFile": "banner_astaria.png"
    },
    {
        "name": "Federation 2 Community Edition",
        "hostUrl": "play.federation2.com",
        "port": 30003,
        "tlsEnabled": false,
        "websiteInfo": "<a href='https://federation2.com'>Website</a><br><a href='https://discord.gg/FB2xzAc5CT'>Discord</a>",
        "icon": ":/icons/fed2-logo.png",
        "description": "Federation 2, the space trading game, is a massively multi-player game set within an exciting world of interstellar commerce and intrigue, in which you interact and collaborate with lots of other players in real-time, and compete against them to climb the ranks. The aim of the game is to amass a larger fortune (in Imperial Groats) than any other player, and to climb the ranks by forging alliances and making friends with the right people. Cooperation is the name of the game in Federation.\n",
        "iconFile": "fed2-logo.png"
    },
    {
        "name": "Imperian",
        "hostUrl": "imperian.com",
        "port": 4000,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://www.imperian.com/'>Website</a><br><a href='https://discord.gg/QX42sY8E7U'>Discord</a>",
        "icon": ":/icons/imperian.png",
        "description": "Imperian was made for conflict.\n\nRivalry matters here. Pressure matters. Momentum matters. Nothing feels softened, and very little is handed to you. That harder edge is exactly what veterans remember.\n\nImperian has always been about conflict with teeth and reputation earned the hard way.\n\nIf you want fantasy that hits harder and asks more of you, start here.",
        "iconFile": "imperian.png"
    },
    {
        "name": "WoTMUD",
        "hostUrl": "game.wotmud.org",
        "port": 2224,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://www.wotmud.org/'>Main website</a><br><a href='http://www.wotmod.org/'>Forums</a>",
        "icon": ":/icons/wotmudicon.png",
        "description": "WoTMUD is the most popular on-line game based on the late Robert Jordan's epic Wheel of Time fantasy novels.\n\nNot only totally FREE to play since it started in 1993 it was officially sanctioned by the Author himself.\n\nExplore a World very like that of Rand al'Thor's; from the Blight in the North down to the Isle of Madmen far, far south.\n\nWander around in any of the towns from the books such as Caemlyn, Tar Valon or Tear, or start your adventure in the Two Rivers area, not YET the home of the Dragon Reborn.\n\nWill you join one of the Clans working for the triumph of the Light over the creatures and minions of the Dark One; or will you be one of the returning invaders in the South West, descendants of Artur Hawkwing's long-thought lost Armies; or just maybe you are skilled enough to be a hideous Trolloc, creature of the Dark, who like Humans - but only as a source of sustenance.\n\nVery definitely a Player Verses Player (PvP) world but with strong Role Playing (RP) too; nowhere is totally safe but some parts are much more dangerous than others - once you enter you may never leave...",
        "iconFile": "wotmudicon.png"
    },
    {
        "name": "Midnight Sun 2",
        "hostUrl": "midnightsun2.org",
        "port": 3000,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://midnightsun2.org/'>http://midnightsun2.org/</a>",
        "icon": ":/icons/midnightsun2.png",
        "description": "Midnight Sun is a medieval fantasy LPmud that has been around since 1991. We are a non-PK, hack-and-slash game, cooperative rather than competitive in nature, and with a strong sense of community.",
        "iconFile": "midnightsun2.png"
    },
    {
        "name": "Luminari",
        "hostUrl": "luminarimud.com",
        "port": 4100,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://www.luminarimud.com/'>http://www.luminarimud.com/</a>",
        "icon": ":/icons/luminari_icon.png",
        "description": "Luminari is a deep, engaging game set in the world of the Luminari - A place where magic is entwined with the fabric of reality and the forces of evil and destruction are rising from a long slumber to again wreak havoc on the realm.  The gameplay of Luminari will be familiar to anyone who has played Dungeons and Dragons, Pathfinder or any of the many RPG systems based on the d20 ruleset.",
        "iconFile": "luminari_icon.png"
    },
    {
        "name": "Starmourn",
        "hostUrl": "starmourn.com",
        "port": 3000,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://www.starmourn.com/'>Website</a><br><a href='https://discord.gg/H8m7pFV'>Discord</a>",
        "icon": ":/icons/starmourn.png",
        "description": "Starmourn offers a galaxy with real edge.\n\nFactions, syndicates, aliens, cybernetics, advanced tech, and a style all its own make Starmourn feel different from the usual fantasy loop. It is a universe built around danger, ambition, and the chance to carve out a name where safety was never promised.\n\nThe future is open. Take your place in it.",
        "iconFile": "starmourn.png"
    },
    {
        "name": "StickMUD",
        "hostUrl": "stickmud.com",
        "port": 7670,
        "tlsEnabled": true,
        "websiteInfo": "<a href='http://www.stickmud.com/'>stickmud.com</a>",
        "icon": ":/icons/stickmud_icon.jpg",
        "description": "StickMUD is a free, medieval fantasy game with a graphical user interface and a depth of features. You are welcomed into the game world with maps and dashboards to complement your imagination. Newbies escape quickly into game play with minimal study time. Awaken under the wondrous Mallorn Tree in the center of Newbie Park and learn by playing. Challenge non-player characters to gain experience, advance level and maximize your stats. Between battles, sit on the enchanted bench under the Tree to rapidly heal and reduce wait time. Signs in the park present game features such as races, clans and guilds. Read up on teasers about the adventures on the path ahead like dragons, castles and sailing. Join a guild and learn the ways of a Bard, Fighter, Mage, Necromancer, Ninja, Thief, Healer or Priest. Train skills in both craft and combat aligned with your guild. Participate in frequent game-wide events to earn points exchanged for gold, experience or skill training. Heroes and villains alike are invited! Role play is optional and player vs. player combat is allowed in much of the game. StickMUD was born in Finland in June 1991 and is now hosted in Canada. Our diverse community of players and active game engineers are ready to welcome new players like you to one of the best text-based multi-player games ever!",
        "iconFile": "stickmud_icon.jpg"
    },
    {
        "name": "Clessidra",
        "hostUrl": "mud.clessidra.it",
        "port": 4000,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://www.clessidra.it/'>http://www.clessidra.it</a>",
        "icon": ":/icons/clessidra.jpg",
        "description": "Clessidra e' il primo MUD completamente in italiano mai creato. Su Clessidra potrete trovare solo aree originali ed in italiano. Molte caratteristiche rendono Clessidra uno dei migliori, se non il migliore, MUD in Italia : Avanzati sistemi di spostamento, sfide uno-contro-uno contro gli amici, o i nemici, L'arena e i combattimenti, Le sfide all'ultimo sangue e i MOB intelligenti con le loro Quest e tecniche di combattimento, un sistema di assegnazione di missioni casuali e un avanzatissimo sistema di Clan che permettera' guerre e conquiste. Disponibilità di mercenari in caso di poca utenza, sistema di produzione/mercato per ottenere esclusivi oggetti, un interfaccia grafica per aiutarti a giocare, sia per i novizi che gli esperti. Un MUD che si evolve di continuo.",
        "iconFile": "clessidra.jpg"
    },
    {
        "name": "Reinos de Leyenda",
        "hostUrl": "reinosdeleyenda.es",
        "port": 23,
        "tlsEnabled": false,
        "websiteInfo": "<a href='https://www.reinosdeleyenda.es/'>Sitio web principal</a><br><a href='https://www.reinosdeleyenda.es/foro/'>Foros</a><br><a href='https://wiki.reinosdeleyenda.es/'>Wiki</a>",
        "icon": ":/icons/reinosdeleyenda_mud.png",
        "description": "El mud Español gratis con más de 20 años de historia.\n\nReinos de Leyenda toma lugar en el siempre cambiante mundo de Eirea, devastado por las intrigas de los dioses tras más de un millar de años de desprecio y cruenta guerra entre sus fanáticos peones mortales.\n\nLa historia se escribe día a día, tomando en consideración las elecciones de los jugadores para decidir las consecuencias irreversibles de este conflicto imperecedero.\n\nÉste es un MUD con PvP que permite al jugador establecer cuánto quiere arriesgar al morir: a más riesgo, más gloria ganará por sus heroicidades. La interpretación (Rol) no está obligada, pero si recompensada con habilidades especiales -no orientadas al combate- y tesoros únicos.\n\nEl detallado creador del juego te permitirá elegir tu deidad -o renegar completamente de los dioses- y unirte a uno de los reinos que los jugadores se encargan de gobernar para explorar un mundo viviente, sumergirte en los misterios del océano, dar forma a tu legado, forjar maravillas olvidadas para ti -o tus aliados- y luchar por fe, gloria o dinero.",
        "iconFile": "reinosdeleyenda_mud.png"
    },
    {
        "name": "Fierymud",
        "hostUrl": "fierymud.org",
        "port": 4000,
        "tlsEnabled": false,
        "websiteInfo": "<a href='https://www.fierymud.org/'>https://www.fierymud.org</a>",
        "icon": ":/icons/fiery_mud.png",
        "description": "The original vision of FieryMUD was to create a challanging MUD for advanced players. This new reborne Fiery is a hope to bring back the goals of the past by inflicting certain death on unsuspecting players. FieryMUD will continue to grow and change through the coming years and those players who seek challenge and possess imagination will come in search of what the 3D world fails to offer them.",
        "iconFile": "fiery_mud.png"
    },
    {
        "name": "Mudlet self-test",
        "hostUrl": "mudlet.org",
        "port": 23,
        "tlsEnabled": false,
        "websiteInfo": "<a href='https://www.mudlet.org'>www.mudlet.org",
        "icon": "",
        "description": "This isn't a game profile, but a special one for testing Mudlet itself using Busted. You can also use it as a starting point to create automated tests for your own profiles!"
    },
    {
        "name": "Accursed Lands",
        "hostUrl": "mud.accursed-lands.com",
        "port": 7979,
        "tlsEnabled": true,
        "websiteInfo": "<a href='https://www.accursed-lands.net'>www.accursed-lands.net</a><br>Discord<br><a href='https://discord.gg/pUPdVra'>https://discord.gg/pUPdVra</a>",
        "icon": ":/icons/accursed_lands.png",
        "description": "Accursed Lands is a long-standing text-based online role-playing game (MUD) with a post-apocalyptic medieval setting.  It offers a \"Role-Play Enforced\" environment without alignments, character levels, or classes, allowing players to choose their own fate and live their character's life as they see fit. Players can expect a community-focused, immersive sandbox experience focusing on freedom with fewer restrictions on their actions.  The game also boasts strong support for visually impaired players, complex magic and crafting, permanent housing, terrain/weather systems, and a vast global map with millions of areas to explore.  Whether seeking adventure, knowledge, fortune, or more, craft your unique story in a world designed to test your every step.\n\nIf you enjoy a slower-paced, skill-based MUD with a richly detailed world and a strong emphasis on role-playing,  Accursed Lands may be the perfect fit for you. We would be happy to have you!",
        "iconFile": "accursed_lands.png"
    },
    {
        "name": "BlackMUD",
        "hostUrl": "blackmud.com",
        "port": 2000,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://www.blackmud.com'>www.blackmud.com</a>",
        "icon": ":/icons/blackmud.png",
        "description": "The world of Entia is a wonderous and challenging place, set within an medieval/fantasy theme and boasting over 90 original areas, made up of tens of thousands of rooms (and still growing and improving in quality), all designed around an original comprehensive world theme and history. BlackMUD is combat-centric but we do encourage and reward roleplaying for those who wish to participate. The story of Entia revolves around a continuing war in which the forces of chaos seek to Unmake the universe itself. It is a time of fear and darkness. It is a time for those with courage, to step forward and defend their beliefs, and their very existence.",
        "iconFile": "blackmud.png"
    },
    {
        "name": "Carrion Fields",
        "hostUrl": "carrionfields.net",
        "port": 4449,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://www.carrionfields.net'>www.carrionfields.net</a>",
        "icon": ":/icons/carrionfields.png",
        "description": "Carrion Fields is a unique blend of high-caliber roleplay and complex, hardcore player-versus-player combat that has been running continuously, and 100% free, for over 30 years.\n\nChoose from among 21 races, 17 highly customizable classes, and several cabals and religions to suit your playstyle and the story you want to tell. Our massive, original world is full of secrets and envied limited objects that take skill to acquire and great care to keep.\n\nWe like to think of ourselves as the Dark Souls of MUDs, with a community that is supportive of new players - unforgiving though our world may be. Join us for a real challenge and real rewards: adrenaline-pumping battles, memorable quests run by our volunteer immortal staff, and stories that will stick with you for a lifetime.",
        "iconFile": "carrionfields.png"
    },
    {
        "name": "Cleft of Dimensions",
        "hostUrl": "cleftofdimensions.net",
        "port": 4354,
        "tlsEnabled": false,
        "websiteInfo": "<a href='https://www.cleftofdimensions.net/'>cleftofdimensions.net</a><br><a href='https://discord.gg/cSqkpbu'>Discord Guild</a>",
        "icon": ":/icons/cleftofdimensions.png",
        "description": "Do you have a soft spot for an old SNES RPG? Are you a fan of retro gaming? The Cleft of Dimensions is an adventure-driven MUD with content inspired by a variety of classic video games. Do you want to jump on goombas? Maybe you'd rather immolate them with lava or bombard them with meteors. Then again, why fight when enslavement's an option? If that doesn't work out, you've got this motorcycle you could crash into them. The Cleft has 16 character classes, each with a distinctive playstyle.\n\nGameplay in the Cleft features exploration, puzzles, quests, and combat. At time of writing, the world contains 98 areas. Quests range from deciphering treasure maps and committing industrial espionage to seeking the blessings of the mana spirits or just going fishing. A remort system facilitates repeat playthroughs to find content you missed the first time around.\n\nThe Cleft opened in July 2000 and has been in active development ever since. We're always innovating. Recent features include Discord integration and areas written with artificial intelligence. Check us out!",
        "iconFile": "cleftofdimensions.png"
    },
    {
        "name": "Legends of the Jedi",
        "hostUrl": "legendsofthejedi.com",
        "port": 5656,
        "tlsEnabled": false,
        "websiteInfo": "<a href='https://www.legendsofthejedi.com/'>legendsofthejedi.com</a>",
        "icon": ":/icons/legendsofthejedi_120x30.png",
        "description": "Legends of the Jedi is a text-based roleplaying experience that immerses players in a multiplayer world where they can rewrite classic Star Wars stories with their own heroes, villains, battles, and endings. Over the course of each two-year timeline, the game explores all the key eras of the Star Wars Expanded Universe.\n\nTake and hold planets as an Imperial Stormtrooper, command the Rebel navy and liberate the galaxy, pursue targets as a bounty hunter, or shape things on a larger scale as a member of the Galactic Senate. Maybe you'll even be one of the few born with force sensitivity, destined to be trained by Jedi or Sith.\n\nThe game offers an extensive crafting system for engineers to supply weapons, armor, and ships to the galaxy. Develop new, cutting-edge armaments to give your side an edge, or open a shop in a bustling commercial district and become wealthy as part of a powerful engineering conglomerate.\n\nLOTJ offers full PVP in both ground and space combat, governed by a set of rules to minimize griefing and ensure that all kills have sufficient in-character cause.\n\nWhat role will you play? The legend awaits!",
        "iconFile": "legendsofthejedi_120x30.png"
    },
    {
        "name": "Multi-Users in Middle-earth",
        "hostUrl": "mume.org",
        "port": 4242,
        "tlsEnabled": true,
        "websiteInfo": "<a href='https://mume.org/'>mume.org</a>",
        "icon": ":/icons/mume.png",
        "description": "Multi-Users in Middle-earth (MUME) is a highly competitive world PvP DikuMUD, set in J. R. R. Tolkien’s fictional world of Middle-earth, as described in The Hobbit and The Lord of the Rings, where players may choose to join the epic war between the forces of Sauron and the armies of the Free peoples. In MUME players can explore, role-play, acquire achievements, and complete quests across many challenging locations across Middle-earth such as Lothlórien, the Shire, Bree, Rivendell, Goblin-town, Mirkwood, Dol Guldur, and the Mines of Moria. The game is completely at no cost to play and has been continually enhanced since its inception in the fall of 1991.",
        "iconFile": "mume.png"
    },
    {
        "name": "MorgenGrauen",
        "hostUrl": "mud.morgengrauen.info",
        "port": 4712,
        "tlsEnabled": true,
        "websiteInfo": "<a href='http://morgengrauen.info/'>MorgenGrauen Webseite</a><br><a href='https://www.youtube.com/MorgenGrauen'>YouTube Kanal</a><br><a href='https://discord.gg/nHJnYHk'>Discord Server</a>",
        "icon": ":/icons/morgengrauen_480x120.png",
        "description": "Willkommen im Morgengrauen, dem größten deutschsprachigen MUD, das seit 1992 kontinuierlich weiterentwickelt wird.\n\nEntdecke hunderte einzigartige Abenteuer! Steigere Deine Fähigkeiten in besonderen Gilden: Dämonische Krieger des Chaos, betrunkene Bierschüttler, Werwölfe, Orks, Elfen, und viele weitere.\n\nUnsere freundliche Spielerschaft hilft Dir gerne bei Deinen ersten Schritten.\n\nSpiel jetzt oder nie!",
        "alternateHostUrls": [
            "mg.mud.de",
            "mg.morgengrauen.info",
            "morgengrauen.info"
        ],
        "iconFile": "morgengrauen_480x120.png"
    },
    {
        "name": "Infinity",
        "hostUrl": "infinitymud.com",
        "port": 4242,
        "tlsEnabled": false,
        "websiteInfo": "<a href='https://infinitymud.com/'>infinitymud.com</a>",
        "icon": ":/icons/infinity_480x120.png",
        "description": "Prepare to immerse yourself in Infinity, a city between times and dimensions that allows entry into any number of lands and timelines. Infinity LPMud provides willing adventurers and questseekers with a venue of original ideas, mind boggling quests, and bloodcurdling beasts, spinning into realms of power, magic, and technology, and many players with which to share your adventures.",
        "iconFile": "infinity_480x120.png"
    },
    {
        "name": "Medievia",
        "hostUrl": "medievia.com",
        "port": 4000,
        "tlsEnabled": false,
        "websiteInfo": "<a href='http://medievia.com/'>Medievia</a>",
        "icon": ":/icons/medievia.png",
        "description": "If you take the deepest and most advanced game possible, and mix it with the best chat world around, what you have is Medievia.\n\nImagine...\n    Endless player-created areas to explore for the first time.\n    Ships you can take out to sea. You can go crabbing, kill monsters, attack other ships, explore new islands, etc.\n    Dragons that hunt you, good dragons that fly you places, dragon lairs you can defeat, etc.\n    Trading for gold where you take goods via covered wagon/mules across the wilderness through adventure after adventure from trade post to trade post. Now you can even go right under the ocean to undersea trading posts.\n    Player vs Player action in zones, ships, wilderness, herobattles, arenas, CPK, NPK, LPK, etc.\n    Joining a clan, the clan can join a town, or go ahead and make their own town in the wilderness.\n    Giving birth and creating your own bloodline. If your bloodline gets big enough you can build homes and castles.\n    A game that has the intuition to track your happiness, pride, sadness, and fear while changing itself to fit your needs!\n    Weather, storms, wind, fire, floods, disease, even asteroids. This may be text but it is the most dynamic game ever attempted. The wind affects the ships, where fire spreads, and even how some critters smell you if you are upwind from them.\n\nDo you dare enter?",
        "iconFile": "medievia.png"
    },
    {
        "name": "Dragonfire MUD",
        "hostUrl": "dragonfiremud.com",
        "port": 1999,
        "tlsEnabled": false,
        "websiteInfo": "<a href='https://www.dragonfiremud.com/'>https://www.dragonfiremud.com/</a>",
        "icon": ":/icons/dragonfire_icon.png",
        "description": "Dragonfire MUD is an ancient LPMUD that has been online since 1989, offering deep lore and a classic text-based RPG experience. It features 16 distinctive guilds, over 10,000 unique rooms, and hundreds of custom quests that you can tackle at your own pace.\n\nExplore realms spanning fantasy, modern, future, and shadowy secrets, hunt dragons for experience and loot, and discover hidden areas and guilds. Optional player killing is allowed, and the community welcomes new adventurers and builders alike.",
        "iconFile": "dragonfire_icon.png"
    },
    {
        "name": "Beyond the Void MUD",
        "hostUrl": "voidmud.com",
        "port": 2201,
        "tlsEnabled": false,
        "websiteInfo": "<a href='https://www.voidmud.com/'>https://www.voidmud.com/</a>",
        "icon": ":/icons/voidmud_icon.png",
        "description": "Beyond the Void is an EverQuest-inspired text RPG that brings the world of Norrath to life with a reimagined storyline touched by an ancient alien race and its rift stones for fast travel. The Void serves as a central hub with trainers, guild masters, and trade for every profession.\n\nFree to play and ready for adventurers, the game emphasizes classic EverQuest combat in a modern text-only experience. Build a character with up to three classes, pursue epic quests and rebirth bonuses, and enjoy quality-of-life features like a custom Mudlet UI and real-time maps.",
        "iconFile": "voidmud_icon.png"
    },
    {
        "name": "Pku XKX MUD",
        "hostUrl": "pkuxkx.net",
        "port": 8081,
        "tlsEnabled": false,
        "websiteInfo": "<a href='https://www.pkuxkx.net/'>https://www.pkuxkx.net/</a>",
        "icon": ":/icons/pkuxkx.png",
        "description": "Peking University Heroes (pkuxkx) was first launched on Peking University in 1996. To date, it has over 80 map areas, 10000+ rooms and more than 20 martial arts sects. It boasts over 200 daily active users and is the oldest and most popular Chinese MUD in the Chinese community.\nWebsite: https://pkuxkx.net/\n\n北大侠客行(pkuxkx)于1996年开始架于北大. 迄今为止，它已经拥有了超过80个地图区域，10000多个房间，20多个武林门派。每日活跃用户有200多人。是华人社区中历史最悠久玩家最多的中文MUD。\n官网: https://pkuxkx.net/；论坛：https://pkuxkx.net/forum/forum.php；WIKI：https://pkuxkx.net/wiki/\n国内(GBK编码) mud.pkuxkx.net:8080； 国内(UTF编码) mud.pkuxkx.net 8081；\n海外转发：https://pkuxkx.net/proxy_status.php 查找推荐线路",
        "iconFile": "pkuxkx.png"
    },
    {
        "name": "Icesus",
        "hostUrl": "icesus.org",
        "port": 4443,
        "tlsEnabled": true,
        "websiteInfo": "<a href='https://www.icesus.org/'>Website</a><br><a href='https://discord.gg/j9cSPyAzQb'>Discord</a>",
        "icon": ":/icons/icesus_480x120.png",
        "description": "Icesus is a free fantasy text RPG running since 1995. Actively developed, community-run, and full of deep systems.\n\nBuild a character from 27 races and 16 guilds. Fight in tactical party combat, explore the frozen Valley of Aegic, and earn your place in player-driven provinces.\n\nOld-school depth. Modern access. New players welcome.",
        "iconFile": "icesus_480x120.png"
    },
    {
        "name": "PhoenixMUD",
        "hostUrl": "phoenixmud.net",
        "port": 4000,
        "tlsEnabled": false,
        "websiteInfo": "<a href='https://phoenixmud.net'>Website</a><br><a href='https://phoenixmud.net/PhoenixMUD.mpackage'>Mudlet package</a>",
        "icon": ":/icons/phoenixmud_480x120.png",
        "description": "PhoenixMUD is a free classic DikuMUD, online since 1996. 20,685 rooms across 276 zones, 16 classes and 15 races, and 400+ levels of progression: 1-100 to Hero, then three full remort climbs.\n\nOur official Mudlet package installs itself on connect: GMCP vitals and effects panes, channel routing into chat windows, and an embedded mapper preloaded with the whole world. The browser client adds a World Atlas: a live map with fog-of-war and route-finding.\n\nNo payment of any kind, and character creation is open. Actively developed, with a friendly community that makes room for newcomers. New players welcome.",
        "iconFile": "phoenixmud_480x120.png"
    }
];

/** The bundled game called `name`, matched the way Mudlet matches it
 *  (TGameDetails::findGame — exact, case-sensitive). */
export function findBundledGame(name: string): BundledGame | null {
    return BUNDLED_GAMES.find(g => g.name === name) ?? null;
}

/** Whether the game reachable at `hostUrl` installs its own full interface,
 *  in which case the generic starter UI is not preinstalled (Mudlet's
 *  TGameDetails::gameProvidesOwnUi). */
export function gameProvidesOwnUi(hostUrl: string): boolean {
    const wanted = hostUrl.toLowerCase();
    return BUNDLED_GAMES.some(g => g.providesOwnUi
        && (g.hostUrl.toLowerCase() === wanted
            || (g.alternateHostUrls ?? []).some(u => u.toLowerCase() === wanted)));
}
